import {StyleSheet, Dimensions} from 'react-native';
import colors from './colors';

const {height, width} = Dimensions.get('screen');

export default styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.WHITE,
  },
  loading: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.TRANSPARENT,
  },
  header: {
    height: 60,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  body: {
    height: height * 0.93,
    paddingBottom: 50,
  },
  title: {
    fontSize: 25,
    fontWeight: 600,
    textAlign: 'center',
  },
  text: {
    fontSize: 17,
  },
  textH: {
    fontSize: 18,
  },
  textHighlight: {
    fontSize: 23,
    fontWeight: 700,
  },
  highlight: {
    fontSize: 19,
    fontWeight: 'bold',
    color: colors.MAINCOLOR,
  },
  textWarn: {
    fontSize: 19,
    fontWeight: 'bold',
    color: colors.RED,
  },
  textI: {
    fontSize: 17,
    fontWeight: 700,
    fontStyle: 'italic',
  },
  textU: {
    fontSize: 18,
    fontWeight: 'bold',
    textDecorationLine: 'underline',
    color: colors.MAINCOLOR,
  },
  textUb: {
    fontSize: 18,
    fontWeight: 'bold',
    textDecorationLine: 'underline',
    color: colors.GRAY,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dropdownSearch: {
    borderRadius: 30,
    paddingLeft: 5,
  },
  login: {
    imageCon: {
      height: height * 0.4,
      justifyContent: 'center',
      alignItems: 'center',
      paddingTop: 20,
    },
    image: {
      width: width * 0.7,
      height: height * 0.7,
      resizeMode: 'contain',
    },
    body: {
      height: height * 0.4,
      marginHorizontal: 20,
      justifyContent: 'space-between',
      padding: 20,
      backgroundColor: colors.WHITE,
    },
    footer: {
      height: height * 0.2,
      alignItems: 'center',
      justifyContent: 'center',
      paddingBottom: 20,
    },
    button: {
      width: 180,
    },
    option: {
      height: height * 0.1,
      justifyContent: 'space-evenly',
      alignItems: 'center',
    },
    optionLine: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      height: height * 0.05,
      width: width * 0.5,
    },
  },
  register: {
    image: {
      height: height * 0.3,
      justifyContent: 'center',
      alignItems: 'center',
      paddingTop: 25,
    },
    body: {
      height: height * 0.5,
      paddingHorizontal: 30,
      justifyContent: 'space-evenly',
    },
    footer: {
      height: height * 0.2,
      alignItems: 'center',
      justifyContent: 'space-evenly',
      padddingVertical: 25,
    },
    button: {
      width: 180,
    },
    textInput: {
      borderRadius: 20,
      borderWidth: 2,
      borderColor: colors.GRAY,
      height: 50,
      paddingHorizontal: 20,
      fontSize: 20,
    },
  },
  home: {
    container: {
      flex: 1,
    },
    text: {
      fontSize: 14,
      fontWeight: 500,
      textAlign: 'center',
      marginTop: 5,
    },
    titleField: {
      width: width,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 10,
    },
    titleCon: {
      width: width * 0.9,
      height: 45,
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      backgroundColor: colors.MAINCOLOR,
      justifyContent: 'center',
      paddingHorizontal: 20,
      borderBottomWidth: 1,
      borderColor: colors.SECONDCOLOR,
    },
    content: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      borderBottomLeftRadius: 26,
      borderBottomRightRadius: 26,
      backgroundColor: '#rgba(255,255,255,0.4)',
      width: width * 0.9,
    },
    itemCon: {
      width: width * 0.3,
      height: height * 0.17,
      padding: 10,
    },
    item: {
      width: '100%',
      height: '100%',
      borderRadius: 30,
      justifyContent: 'space-evenly',
      alignItems: 'center',
    },
    image: {
      width: width * 0.23,
      height: height * 0.1,
      resizeMode: 'contain',
    },
    bannerCon: {
      width: width,
      height: height * 0.25,
    },
    banner: {
      width: width,
      height: height * 0.25,
      resizeMode: 'contain',
    },
    title: {
      fontSize: 21,
      color: colors.WHITE,
      fontWeight: 500,
      fontStyle: 'italic',
    },
    logo: {
      fontSize: 40,
      color: colors.MAINCOLOR,
      fontWeight: 500,
      // fontFamily: 'DancingScript-Bold',
    },
  },

  boxChat: {
    position: 'absolute',
    right: 10,
    bottom: 30,
  },
  dmcty: {
    body: {
      height: height * 0.93,
      padding: 20,
    },
    dropdown: {
      width: 150,
      height: 40,
      borderWidth: 2,
      borderColor: colors.GRAY,
      paddingLeft: 10,
      paddingRight: 5,
      marginLeft: 10,
      borderBottomLeftRadius: 30,
      borderTopLeftRadius: 30,
      justifyContent: 'center',
    },
    dropdownQuy: {
      width: 70,
      height: 40,
      borderColor: colors.GRAY,
      borderWidth: 2,
      paddingLeft: 20,
      paddingRight: 10,
      borderRadius: 30,
    },
    dropdownNam: {
      width: 100,
      height: 40,
      borderColor: colors.GRAY,
      borderWidth: 2,
      paddingLeft: 20,
      paddingRight: 10,
      borderRadius: 30,
    },
    content: {
      minHeight: 60,
      justifyContent: 'center',
      marginBottom: 10,
    },
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 50,
      marginBottom: 10,
    },
    modalView: {
      flex: 1,
      justifyContent: 'center',
      backgroundColor: colors.TRANSPARENT,
    },
    calendar: {
      backgroundColor: colors.WHITE,
      padding: 30,
      borderRadius: 20,
      alignItems: 'center',
      marginTop: 20,
    },
    buttonCon: {
      flexDirection: 'row',
      justifyContent: 'center',
      paddingTop: 20,
    },
    input: {
      width: 320,
      marginTop: 30,
    },
    leftCol: {
      width: width * 0.6,
      paddingLeft: 25,
      paddingRight: 10,
    },
    rightCol: {
      width: width * 0.4,
      paddingRight: 20,
      alignItems: 'flex-end',
    },
    calendarButton: {
      borderBottomLeftRadius: 20,
      borderTopLeftRadius: 20,
      width: 150,
      borderWidth: 1.5,
      borderColor: colors.SECONDCOLOR,
    },
    calendarButtonR: {
      borderBottomRightRadius: 20,
      borderTopRightRadius: 20,
      width: 150,
      borderWidth: 1.5,
      borderColor: colors.SECONDCOLOR,
    },
    containerMst: {
      marginLeft: 10,
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
      borderWidth: 2,
      borderColor: colors.GRAY,
      backgroundColor: colors.WHITE,
      width: 140,
    },
    containerQuy: {
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
      borderWidth: 2,
      borderColor: colors.GRAY,
      backgroundColor: colors.WHITE,
      width: 50,
      marginLeft: 10,
    },
    containerNam: {
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
      borderWidth: 2,
      borderColor: colors.GRAY,
      backgroundColor: colors.WHITE,
      width: 80,
      marginLeft: 10,
    },
    hyperlink: {
      textAlign: 'center',
      fontSize: 16,
      fontStyle: 'italic',
      color: colors.RED,
      textDecorationLine: 'underline',
    },
  },
  info: {
    body: {
      height: height * 0.93,
      backgroundColor: colors.WHITE,
      paddingBottom: 40,
    },
    row: {
      height: 50,
      justifyContent: 'center',
      borderBottomWidth: 2,
      borderColor: colors.GRAY,
      marginTop: 20,
      paddingHorizontal: 10,
    },
    text: {
      fontSize: 23,
      fontWeight: 600,
    },
    title: {
      fontSize: 25,
      fontWeight: 'bold',
      fontStyle: 'italic',
    },
    content: {
      paddingHorizontal: 15,
    },
    imageCon: {
      width: width,
      alignItems: 'center',
      justifyContent: 'center',
    },
    image: {
      width: width * 0.8,
      height: height * 0.25,
      resizeMode: 'contain',
    },
    logo: {
      fontSize: 40,
      color: colors.MAINCOLOR,
    },
    hyperlink: {
      color: colors.MAINCOLOR,
      fontWeight: 700,
      fontSize: 23,
      fontStyle: 'italic',
      textDecorationLine: 'underline',
    },
  },
  lh: {
    row: {
      alignItems: 'center',
      paddingHorizontal: 20,
    },
    contentRow: {
      flexDirection: 'row',
      alignItems: 'center',
      height: 50,
    },
  },
  dshoadon: {
    itemWrapper: {
      borderBottomWidth: 2,
      borderColor: colors.GRAY,
      padding: 10,
      backgroundColor: colors.WHITE,
    },
    dropdown: {
      width: 70,
      height: 30,
      borderWidth: 2,
      borderColor: colors.GRAY,
      borderRadius: 30,
      paddingLeft: 15,
      paddingRight: 5,
    },
    deleteButton: {
      backgroundColor: colors.RED,
      width: width * 0.2,
      alignItems: 'center',
      justifyContent: 'center',
    },
    filterCon: {
      width: width,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
    },
    dropdownFilter: {
      width: width * 0.5,
      height: 40,
      borderWidth: 2,
      borderColor: colors.GRAY,
      borderBottomLeftRadius: 30,
      borderTopLeftRadius: 30,
      paddingLeft: 20,
      paddingRight: 10,
    },
    containerStyle: {
      marginLeft: 15,
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
      borderWidth: 2,
      borderColor: colors.GRAY,
      backgroundColor: colors.WHITE,
      width: 200,
    },
    containerStyle1: {
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
      borderWidth: 2,
      borderColor: colors.GRAY,
      backgroundColor: colors.WHITE,
      width: 60,
    },
    row: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      height: 35,
    },
    body: {
      height: height * 0.83,
    },
    button: {
      borderBottomRightRadius: 30,
      borderTopRightRadius: 30,
      width: 100,
    },
  },
  hoadon: {
    row: {
      flexDirection: 'row',
      justifyContent: 'center',
      marginBottom: 15,
    },
    leftCol: {
      width: width * 0.3,
      alignItems: 'flex-start',
      paddingLeft: 10,
    },
    rightCol: {
      width: width * 0.7,
      paddingRight: 10,
    },
    tbph: {
      alignItems: 'flex-end',
      marginBottom: 20,
      paddingHorizontal: 20,
      width: 200,
    },
    cash: {
      marginTop: 10,
      paddingHorizontal: 20,
    },
    cashRow: {
      minHeight: 35,
      width: width,
      flexDirection: 'row',
      justifyContent: 'flex-end',
    },
    leftColCash: {
      width: width * 0.3,
      alignItems: 'flex-end',
      paddingLeft: 10,
    },
    rightColCash: {
      width: width * 0.7,
      paddingHorizontal: 10,
      alignItems: 'flex-end',
    },
    timeRow: {
      width: width,
      flexDirection: 'row',
      justifyContent: 'flex-end',
      minHeight: 25,
    },
    leftColTime: {
      width: width * 0.45,
      alignItems: 'flex-end',
      paddingLeft: 15,
    },
    rightColTime: {
      width: width * 0.55,
      paddingLeft: 10,
      alignItems: 'flex-start',
    },
  },
  hoadon0: {
    itemWrapper: {
      minHeight: 160,
      padding: 20,
      backgroundColor: colors.WHITE,
    },
    row: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 10,
    },
  },
  hanghoa: {
    itemWrapper: {
      minHeight: 100,
      padding: 20,
    },
    row: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 10,
    },
    dropdown: {
      height: 40,
      width: 90,
      borderRadius: 30,
      borderColor: colors.GRAY,
      borderWidth: 2,
      paddingHorizontal: 10,
      marginTop: 5,
    },
    containerStyle: {
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
      width: 70,
      marginLeft: 10,
      borderWidth: 2,
      borderColor: colors.GRAY,
      backgroundColor: colors.WHITE,
    },
  },
  dscty: {
    itemWrapper: {
      minHeight: 110,
      padding: 20,
      backgroundColor: colors.WHITE,
    },
    button: {
      borderRadius: 60,
      height: 50,
      width: 50,
    },
    buttonCon: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-evenly',
      width: 110,
    },
    lhCon: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 5,
    },
  },
  dscty0: {
    contentRow: {
      minHeight: 40,
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 20,
      width: width,
    },
    leftCol: {
      width: width * 0.45,
      minHeight: 40,
      justifyContent: 'center',
      alignItems: 'flex-end',
    },
    rightCol: {
      width: width * 0.55,
      minHeight: 40,
      justifyContent: 'center',
      alignItems: 'flex-start',
      paddingLeft: 10,
    },
    input: {
      height: 40,
      width: width * 0.45,
      borderWidth: 2,
      borderColor: colors.GRAY,
      borderRadius: 30,
      paddingHorizontal: 15,
      fontSize: 17,
    },
    pmktDropdown: {
      height: 40,
      width: 150,
      borderWidth: 2,
      borderColor: colors.GRAY,
      borderRadius: 30,
      paddingHorizontal: 10,
    },
    lhDropdown: {
      height: 40,
      width: 150,
      borderWidth: 2,
      borderColor: colors.GRAY,
      borderRadius: 30,
      paddingRight: 10,
    },
    ttDropdown: {
      height: 40,
      width: 80,
      borderWidth: 2,
      borderColor: colors.GRAY,
      borderRadius: 30,
      paddingRight: 10,
    },
    ttrangDropdown: {
      height: 40,
      width: width * 0.45,
      borderWidth: 2,
      borderColor: colors.GRAY,
      borderRadius: 30,
    },
    inputStt: {
      height: 40,
      width: width * 0.15,
      borderWidth: 2,
      borderColor: colors.GRAY,
      borderRadius: 30,
      paddingHorizontal: 20,
      fontSize: 17,
      textAlign: 'center',
    },
    buttonCon: {
      position: 'absolute',
      alignSelf: 'center',
      width: 180,
      bottom: width * 0.1,
    },
    containerPmkt: {
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
      borderWidth: 2,
      borderColor: colors.GRAY,
      backgroundColor: colors.WHITE,
      width: 130,
      alignSelf: 'center',
    },
    containerLh: {
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
      borderWidth: 2,
      borderColor: colors.GRAY,
      backgroundColor: colors.WHITE,
      width: 130,
      alignSelf: 'center',
    },
    containerTt: {
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
      borderWidth: 2,
      borderColor: colors.GRAY,
      backgroundColor: colors.WHITE,
      width: 70,
      alignSelf: 'center',
    },
    containerTtrang: {
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      borderWidth: 2,
      borderColor: colors.GRAY,
      backgroundColor: colors.WHITE,
      width: 170,
      height: 270,
      alignSelf: 'center',
    },
  },
  ktruiro: {
    input: {
      width: width * 0.5,
      borderColor: colors.GRAY,
      borderWidth: 2,
      borderBottomLeftRadius: 30,
      borderTopLeftRadius: 30,
      paddingHorizontal: 30,
      fontSize: 18,
      height: 40,
    },
    inputCon: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      minHeight: 100,
    },
    content: {
      height: height * 0.45,
      margin: 30,
      borderRadius: 30,
      padding: 20,
      justifyContent: 'space-evenly',
      borderColor: colors.GRAY,
      borderWidth: 2,
    },
    contentRow: {
      flexDirection: 'row',
      justifyContent: 'center',
      minHeight: 50,
    },
    leftCol: {
      width: width * 0.4,
      paddingLeft: 65,
    },
    rightCol: {
      width: width * 0.7,
      paddingRight: 60,
    },
    button: {
      borderRadius: 30,
      width: 200,
      height: 45,
      alignSelf: 'center',
    },
  },
  taikhoan: {
    text: {
      fontSize: 19,
      fontWeight: '600',
    },
    hyperlink: {
      fontSize: 20,
      fontWeight: 700,
      color: colors.MAINCOLOR,
      textDecorationLine: 'underline',
    },
    buttonCon: {
      flexDirection: 'row',
      justifyContent: 'space-evenly',
      width: '100%',
    },
    infoRow: {
      flexDirection: 'row',
      justifyContent: 'center',
      width: width,
      marginTop: 10,
    },
    leftCol: {
      width: width * 0.35,
      paddingLeft: 20,
      justifyContent: 'center',
    },
    rightCol: {
      width: width * 0.65,
      paddingRight: 20,
      paddingLeft: 10,
      justifyContent: 'center',
    },
  },
  tuvan: {
    dropdown: {
      width: 300,
      height: 45,
      borderRadius: 30,
      borderWidth: 2,
      borderColor: colors.GRAY,
      paddingHorizontal: 10,
      justifyContent: 'center',
    },
    dropdownCon: {
      borderWidth: 2,
      borderColor: colors.GRAY,
      width: 270,
      marginLeft: 15,
      backgroundColor: colors.WHITE,
      borderBottomLeftRadius: 15,
      borderBottomRightRadius: 15,
    },
    dropdownDanhxung: {
      width: 180,
      height: 45,
      borderRadius: 30,
      borderWidth: 2,
      borderColor: colors.GRAY,
      paddingHorizontal: 10,
      justifyContent: 'center',
    },
    dropdownConDanhxung: {
      borderWidth: 2,
      borderColor: colors.GRAY,
      width: 150,
      marginLeft: 15,
      backgroundColor: colors.WHITE,
      borderBottomLeftRadius: 15,
      borderBottomRightRadius: 15,
    },
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
    },
  },
  ehd: {
    text: {
      fontSize: 16,
    },
    itemWrapper: {
      minHeight: 80,
      padding: 20,
      backgroundColor: colors.WHITE,
    },
    dateCon: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
    },
    calendarButton: {
      borderBottomLeftRadius: 20,
      borderTopLeftRadius: 20,
      width: 150,
      borderWidth: 1.5,
      borderColor: colors.MAINCOLOR,
    },
    calendarButtonR: {
      borderBottomRightRadius: 20,
      borderTopRightRadius: 20,
      width: 150,
      borderWidth: 1.5,
      borderColor: colors.MAINCOLOR,
    },
    list: {
      height: height * 0.8,
    },
    info: {
      alignItems: 'center',
    },
    infoRow: {
      flexDirection: 'row',
      marginTop: 5,
      alignItems: 'center',
    },
    infoL: {
      width: width * 0.25,
      minHeight: 40,
      alignItems: 'center',
      paddingLeft: 10,
    },
    infoR: {
      width: width * 0.75,
      minHeight: 40,
      paddingRight: 10,
    },
    product: {
      paddingHorizontal: 20,
    },
    itemRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    button: {
      borderRadius: 30,
      height: 40,
      width: 70,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dropdown: {
      height: 40,
      width: 150,
      borderRadius: 30,
      borderColor: colors.GRAY,
      borderWidth: 2,
      paddingHorizontal: 10,
      marginTop: 5,
    },
    containerStyle: {
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
      width: 130,
      marginLeft: 10,
      borderWidth: 2,
      borderColor: colors.GRAY,
      backgroundColor: colors.WHITE,
    },
    modalSignContent: {
      backgroundColor: colors.WHITE,
      padding: 30,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 20,
      height: 180,
    },
  },
  tdt: {
    dropdown: {
      width: 180,
      height: 40,
      borderWidth: 2,
      borderColor: colors.GRAY,
      paddingLeft: 10,
      paddingRight: 5,
      marginLeft: 10,
      borderRadius: 30,
      justifyContent: 'center',
    },
    dropdownL: {
      width: 170,
      height: 40,
      borderWidth: 2,
      borderColor: colors.GRAY,
      paddingLeft: 10,
      paddingRight: 5,
      marginLeft: 10,
      borderBottomLeftRadius: 30,
      borderTopLeftRadius: 30,
      justifyContent: 'center',
    },
    containerMst: {
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
      borderWidth: 2,
      borderColor: colors.GRAY,
      backgroundColor: colors.WHITE,
      width: 150,
      marginLeft: 15,
    },
    list: {
      height: height * 0.6,
    },
    listnghiavu: {
      height: height * 0.75,
    },
    row: {
      height: 50,
      alignItems: 'center',
      justifyContent: 'space-between',
      borderBottomWidth: 2,
      borderColor: colors.GRAY,
      marginTop: 20,
      flexDirection: 'row',
      paddingHorizontal: 10,
    },
    subrow: {
      height: 50,
      justifyContent: 'center',
      borderBottomWidth: 2,
      borderColor: colors.GRAY,
      marginTop: 10,
      paddingLeft: 30,
    },
    text: {
      fontSize: 21,
      fontWeight: 600,
    },
    rowDay: {
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 50,
      marginBottom: 10,
      width: '50%',
    },
    calendarButton: {
      width: 200,
      borderWidth: 1.5,
      borderColor: colors.SECONDCOLOR,
      borderRadius: 30,
    },
    rowDkt: {
      flexDirection: 'row',
      marginTop: 10,
      flexWrap: 'wrap',
    },
    buttonR: {
      borderBottomRightRadius: 30,
      borderTopRightRadius: 30,
      width: 85,
    },
  },
  dkkd: {
    dropdownLoai: {
      width: 140,
      height: 40,
      borderWidth: 2,
      borderColor: colors.GRAY,
      paddingLeft: 10,
      paddingRight: 5,
      marginLeft: 10,
      borderRadius: 30,
    },
    containerLoai: {
      width: 120,
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
      borderWidth: 2,
      borderColor: colors.GRAY,
      backgroundColor: colors.WHITE,
      marginLeft: 13,
    },
    containerTinh: {
      width: 160,
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
      borderWidth: 2,
      borderColor: colors.GRAY,
      backgroundColor: colors.WHITE,
      marginLeft: 13,
    },
    list: {
      height: height * 0.58,
    },
    bottomModal: {
      backgroundColor: colors.WHITE,
      padding: 10,
      borderRadius: 20,
      height: 200,
    },
    modalView: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: colors.TRANSPARENT,
    },
    swipeButton: {
      backgroundColor: colors.MAINCOLOR,
      width: width * 0.2,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  message: {
    content: {
      height: height * 0.8,
      backgroundColor: colors.WHITE,
    },
  },
});
