export default {
  LOGO: require('../assets/logo.png'),
  LOGO_VH: require('../assets/logoVH.png'),
  ZALO: require('../assets/zalo.png'),
  VAT: require('../assets/vat.jpg'),
  DSCTY: require('../assets/dmcty.png'),
  KTRUIRO: require('../assets/ruiro.jpg'),
  TDT: require('../assets/thuedientu.png'),
  DKKD: require('../assets/dangkykinhdoanh.png'),
  BHXH: require('../assets/bhxh.png'),
  EHD: require('../assets/favicon.png'),
  EKS: require('../assets/hopdongdientu.png'),
  TVT: require('../assets/tuvanthue.jpg'),
  WAIT: require('../assets/ellipse-dots.gif'),
  BG: require('../assets/imagebg.jpg'),
  DEFAULT: require('../assets/defaultImage.png'),
  EBH_BN: require('../assets/ebhBanner.png'),
  EHD_BN: require('../assets/ehdBanner.png'),
  CHAT: require('../assets/online-chat.png'),
};
